deploy_user: automation
jenkins_port: "8082"
url: "http://localhost:{{ jenkins_port }}"
deploy_path: /home/automation/jenkins-job-builder
tag_name: 2.150.1
backup_name: 'default'
admin_name: jeremy
java_opts: "-Xmx4096m -Djenkins.install.runSetupWizard=false -Dhudson.model.DirectoryBrowserSupport.CSP=\"sandbox allow-same-origin allow-scripts; default-src 'none'; script-src 'self' 'unsafe-eval'; img-src 'self'; style-src 'self' 'unsafe-inline'; font-src 'self'\""
jenkins_opts: "--handlerCountMax=300 --logfile=/var/log/jenkins/jenkins.log --webroot=/var/cache/jenkins/war"
